### ISSUE TITLE
USE_CUDA or USE_ASAN compile flag does not work

### ISSUE THREAD

**Issue by cissieAB** [nathanwbrei/phasm#16]
No matter what value USE_CUDA or USE_ASAN is, they are always on in the containerized ubuntu env. Not sure how would it  work bare metal.

Because I revert commit https://github.com/nathanwbrei/phasm/commit/1069a97f6796dbaf4087e20270fc5ebcd14e7e26, we can focus on USE_ASAN istead.

**Comment by nathanwbrei** [comment]
All USE_CUDA does is set `-fsanitize=address` in the compile and link options. Either:
A. CMake is aggressively caching USE_CUDA, and all we need to do is delete the cmake build directory, or
B. Someone else is setting `-fsanitize=address`

**Comment by cissieAB** [comment]
Above is about USE_ASAN? You are right,  I delete `/build` and no msg on memory leakage showed up.
