### ISSUE TITLE
Look into singularity images with higher libtorch/cuda-toolkit support

### ISSUE THREAD

**Issue by cissieAB** [nathanwbrei/phasm#6]
Move all the stuff into a container should make things easier.

**Comment by nathanwbrei** [comment]
Yes please! Are you documenting anywhere the horrible constraint propagation graph? I.e. what compiler version/language standard do we need for each choice of libtorch, CUDA, and GPU hardware?

**Comment by cissieAB** [comment]
https://github.com/nathanwbrei/phasm/blob/cissie_pinn/docs/farm_guide.md

Above it's a guide on installing all the stuff on the farm (expect JANA2.6.0). For this guide
- CUDA: 11.4.2
- libtorch: libtorch-shared-with-deps-1.12.0+cu113.zip
- cudnn: 8.6.0
- gcc/10.2.0, cmake/3.21.1, default pin/dwarf versions

I did not include the JANA version.

The docker image can provide higher CUDA/libtorch versions than the above
